---
abstract: unknown
author:
  - 'Olexandr Sydorchuk'
build_requires:
  ExtUtils::MakeMaker: '0'
  File::Copy::Recursive: '0.38'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 7, CPAN::Meta::Converter version 2.142690'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: CSS_Watcher
no_index:
  directory:
    - t
    - inc
requires:
  CSS::Selector::Parser: '0'
  Carp: '0'
  File::Slurp: '0'
  Log::Log4perl: '0'
  Path::Tiny: '0'
version: '0.3'
